[profile.default]
src = "src"
out = "out"
libs = ["dependencies"]
verbosity = 2
ffi = true

[dependencies]
forge-std = "1.9.2"

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options